### ISSUE TITLE
BUG: alfred.js restart function

### ISSUE THREAD

**Issue by gabotaco** [rhit-corridg/rc-website-server#14]
/root/rc-website-server/app/domain/api/alfred.js:33
        this.successResponse(res);
             ^
TypeError: Cannot read property 'successResponse' of undefined
    at /root/rc-website-server/app/domain/api/alfred.js:20:22
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by gabotaco** [comment]
if you click on edit on the above comment you should be able to view it without the missing white space
![image](https://user-images.githubusercontent.com/42919897/174490350-94a284f6-77d3-4fe2-aaba-caff03069a86.png)
